version: '3'
services:

  plex:
    # https://hub.docker.com/r/plexinc/pms-docker/
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex
    network_mode: host
    env_file:
      - tz.env
    environment:
      # The claim token for the server to obtain a real server token: https://www.plex.tv/claim
      #- PLEX_CLAIM=<claimToken>
      # This variable defines the additional IPs on which the server may be be found
      #- ADVERTISE_IP=http://<hostIPAddress>:32400/
      # The user / group id of the plex user / group created inside the container
      - PLEX_UID=1026
      - PLEX_GID=100
      # IP/netmask entries which allow access to the server without requiring authorization
      #- ALLOWED_NETWORKS=<allowedNetworks>
    #ports:
    #  - '32400:32400/tcp' # for access to the Plex Media Server [required]
    #  - '1900:1900/udp' # for access to the Plex DLNA Server
    #  - '3005:3005/tcp' # for controlling Plex Home Theater via Plex Companion
    #  - '8324:8324/tcp' # for controlling Plex for Roku via Plex Companion
    #  - '32410:32410/udp' # for current GDM network discovery
    #  - '32412-32414:32412-32414/udp' # for current GDM network discovery
    #  - '32469:32469/tcp' # for access to the Plex DLNA Server
    volumes:
      - /volume1/homes/thomas/.media/plex:/config
      - /volume1/media/movies:/data/movies
      - /volume1/media/music:/data/music
      - /volume1/media/tvshows:/data/tvshows

  couchpotato:
    # https://hub.docker.com/r/linuxserver/couchpotato/
    image: linuxserver/couchpotato:latest
    container_name: couchpotato
    hostname: couchpotato
    depends_on:
      - plex
    env_file:
      - tz.env
      - ids.env
    ports:
      - '5050:5050'
    volumes:
      - /volume1/homes/thomas/.media/couchpotato:/config
      - /volume1/media/downloads/couchpotato:/downloads
      - /volume1/media/movies:/movies

  medusa:
    # https://hub.docker.com/r/linuxserver/medusa/
    image: linuxserver/medusa:latest
    container_name: medusa
    hostname: medusa
    depends_on:
      - plex
    env_file:
      - tz.env
      - ids.env
    ports:
      - '8081:8081'
    volumes:
      - /volume1/homes/thomas/.media/medusa:/config
      - /volume1/media/downloads/medusa:/downloads
      - /volume1/media/tvshows:/tv

  ubooquity:
    # https://hub.docker.com/r/linuxserver/ubooquity/
    image: linuxserver/ubooquity:latest
    container_name: ubooquity
    hostname: ubooquity
    env_file:
      - tz.env
      - ids.env
    #environment:
    #  # Set the maximum memory
    #  - MAXMEM=256
    ports:
      - '2202:2202'
      - '2203:2203'
    volumes:
      - /volume1/homes/thomas/.media/ubooquity:/config
      - /volume1/media/books:/books
      - /volume1/media/comics:/comics
